## Feature Selection Techniques


In [ ]:

# Boruta
# Lasso
# Subset(RFE) - Recursive Feature Selection/Elemination
# RandomForest or DecisionTree
# Chi-Square
# p-values into summary


In [11]:
import pandas as pd               
cr = pd.read_csv("E:\Data_Science\datasets\CreditRisk.csv")
cr

Loan_ID Gender Married  Dependents     Education Self_Employed  \
0    LP001002   Male      No         0.0      Graduate            No   
1    LP001003   Male     Yes         1.0      Graduate            No   
2    LP001005   Male     Yes         0.0      Graduate           Yes   
3    LP001006   Male     Yes         0.0  Not Graduate            No   
4    LP001008   Male      No         0.0      Graduate            No   
..        ...    ...     ...         ...           ...           ...   
976  LP002971   Male     Yes         4.0  Not Graduate           Yes   
977  LP002975   Male     Yes         0.0      Graduate            No   
978  LP002980   Male      No         0.0      Graduate            No   
979  LP002986   Male     Yes         0.0      Graduate            No   
980  LP002989   Male      No         0.0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
976             4009             1777.0       113.0             360.0   
977             4158              709.0       115.0             360.0   
978             3250             1993.0       126.0             360.0   
979             5000             2393.0       158.0             360.0   
980             9200                0.0        98.0             180.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
976             1.0         Urban           Y  
977             1.0         Urban           Y  
978             NaN     Semiurban           Y  
979             1.0         Rural           N  
980             1.0         Rural           Y  

[981 rows x 13 columns]

In [12]:
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectFromModel
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [13]:
cr.Gender.replace({"Male":1,"Female":0}, inplace= True)
cr.Married.replace({"No":0, "Yes":1}, inplace = True)
cr.Education.replace({"Graduate":1,"Not Graduate":0}, inplace = True)
cr.Self_Employed.replace({"No":0,"Yes":1},inplace = True)
cr.Property_Area.replace({"Semiurban":1,"Urban":2,"Rural":3}, inplace = True)
cr.Loan_Status.replace({"Y":1,"N":0}, inplace = True)

In [14]:
cr.isnull().sum()   

Loan_ID               0
Gender               24
Married               3
Dependents           25
Education             0
Self_Employed        55
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           27
Loan_Amount_Term     20
Credit_History       79
Property_Area         0
Loan_Status           0
dtype: int64

In [15]:
cr.Credit_History = cr.Credit_History.fillna(0)
cr.Self_Employed = cr.Self_Employed.fillna(1)
cr.LoanAmount = cr.LoanAmount.fillna(cr.LoanAmount.mean())
cr.Dependents = cr.Dependents.fillna(0)
cr.Gender = cr.Gender.fillna(1)
cr.Loan_Amount_Term = cr.Loan_Amount_Term.fillna(cr.Loan_Amount_Term.median())
cr.Married = cr.Married.fillna(0)
cr.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [16]:
cr_x = cr.iloc[:, 1:12]
cr_y = cr.iloc[:, -1]

## Chi - Square Feature Selection 

In [17]:
test = SelectKBest(score_func = chi2, k = 'all')
fited = test.fit(cr_x,cr_y)
fited.scores_ 

array([1.63169749e-01, 2.58761333e+00, 2.26100537e-01, 1.15130425e+00,
       4.78657843e-02, 2.29309933e+03, 9.57513159e+03, 5.05998317e+01,
       2.30673968e+01, 5.73327538e+01, 4.92265988e+00])

In [18]:
list(fited.scores_)

[0.1631697491732269,
 2.587613329148895,
 0.2261005368922207,
 1.1513042479428612,
 0.047865784277152504,
 2293.09933408766,
 9575.131586894373,
 50.59983166997392,
 23.067396760268487,
 57.332753806689,
 4.922659878770546]

## Boruta Feature Selection

In [20]:
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from boruta import BorutaPy
rf = RandomForestClassifier()

In [21]:
cr_x = np.array(cr_x)
cr_y = np.array(cr_y)

In [22]:
boruta_feature_selector = BorutaPy(rf, random_state=111, max_iter = 50, verbose=2, perc = 75)

In [23]:
boruta_feature_selector.fit(cr_x,cr_y)

Iteration: 	1 / 50
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	2 / 50
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	3 / 50
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	4 / 50
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	5 / 50
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	6 / 50
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	7 / 50
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	8 / 50
Confirmed: 	4
Tentative: 	0
Rejected: 	7


BorutaPy finished running.

Iteration: 	9 / 50
Confirmed: 	4
Tentative: 	0
Rejected: 	7


BorutaPy(alpha=0.05,
         estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                          criterion='gini', max_depth=None,
                                          max_features='auto',
                                          max_leaf_nodes=None,
                                          min_impurity_decrease=0.0,
                                          min_impurity_split=None,
                                          min_samples_leaf=1,
                                          min_samples_split=2,
                                          min_weight_fraction_leaf=0.0,
                                          n_estimators=1000, n_jobs=None,
                                          oob_score=False,
                                          random_state=<mtrand.RandomState object at 0x00000261A81C0598>,
                                          verbose=0, warm_start=False),
         max_iter=50, n_estimators=1000, perc=75,
      

In [24]:
boruta_feature_selector.support_

array([False, False, False, False, False,  True,  True,  True, False,
        True, False])

In [25]:
vars = cr.columns
vars

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

## Recursive Feature Elimination/Selection (RFE)

# RFE over DecisionTree

In [27]:
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()

In [28]:
rfe = RFE(dtc, 1)
rfe.fit(cr_x,cr_y)

RFE(estimator=DecisionTreeClassifier(class_weight=None, criterion='gini',
                                     max_depth=None, max_features=None,
                                     max_leaf_nodes=None,
                                     min_impurity_decrease=0.0,
                                     min_impurity_split=None,
                                     min_samples_leaf=1, min_samples_split=2,
                                     min_weight_fraction_leaf=0.0,
                                     presort=False, random_state=None,
                                     splitter='best'),
    n_features_to_select=1, step=1, verbose=0)

In [29]:
rfe.support_

array([False, False, False, False, False,  True, False, False, False,
       False, False])

# RFE over RandomForest

In [30]:
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

In [31]:
rfe = RFE(rf, 3)
rfe.fit(cr_x,cr_y)

C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: Future

RFE(estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                     criterion='gini', max_depth=None,
                                     max_features='auto', max_leaf_nodes=None,
                                     min_impurity_decrease=0.0,
                                     min_impurity_split=None,
                                     min_samples_leaf=1, min_samples_split=2,
                                     min_weight_fraction_leaf=0.0,
                                     n_estimators='warn', n_jobs=None,
                                     oob_score=False, random_state=None,
                                     verbose=0, warm_start=False),
    n_features_to_select=3, step=1, verbose=0)

In [32]:
rfe.support_

array([False, False, False, False, False,  True, False,  True, False,
        True, False])

# RFE over SVM

In [33]:
from sklearn.feature_selection import RFE
from sklearn.svm import LinearSVC
svm = LinearSVC()

In [34]:
rfe = RFE(svm, 4)
rfe.fit(cr_x,cr_y)

C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", Conve

RFE(estimator=LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
                        intercept_scaling=1, loss='squared_hinge',
                        max_iter=1000, multi_class='ovr', penalty='l2',
                        random_state=None, tol=0.0001, verbose=0),
    n_features_to_select=4, step=1, verbose=0)

In [35]:
rfe.support_

array([False,  True, False,  True, False, False, False, False, False,
        True,  True])