# Dataset Reading

In [72]:
import pandas as pd               
#pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)
import numpy as np
md = pd.read_csv("E:\Data_Science\datasets\modeldata.csv")
md

id extract_date        skill  \
0       0002e93c8519f24cc642ca462ef49956   10-01-2017     BEGINNER   
1       0003b2d98410d0350070961653b8c3bc   10-01-2017     BEGINNER   
2       00093099e0d8d7c3d60a22e2883ad63d   10-01-2017     BEGINNER   
3       000eb7f4b843c451d98a249e85328b05   10-01-2017     BEGINNER   
4       001134540564124eb2f767cb0905053c   10-01-2017     BEGINNER   
...                                  ...          ...          ...   
308943  fff800209d3ffa5f2fdcf613c1c6acfc   10-01-2017      UNKNOWN   
308944  fff8404207a324e34193507548d403f9   10-01-2017  EXPERIENCED   
308945  fff867f75f87839661c2f2d2ef458cce   10-01-2017     BEGINNER   
308946  fffe40036ade828aa5633a9d135ae681   10-01-2017      UNKNOWN   
308947  ffffa1cc4c38b8fb0bd0e73583ee9d78   10-01-2017        MIXED   

                       job             purpose                  target_group  \
0                 ACADEMIC     ME_PROFESSIONAL            HED - ED/FAC/STAFF   
1                 ACADEMIC     ME_PROFESSIONAL       EDGEN - AD/ED/FAC/STAFF   
2                      NaN                 NaN                      HOBBYIST   
3                  STUDENT  ME_NONPROFESSIONAL               EDGEN - STUDENT   
4                  STUDENT     ME_PROFESSIONAL               EDGEN - STUDENT   
...                    ...                 ...                           ...   
308943                 NaN                 NaN  DIGITAL IMAGING PROFESSIONAL   
308944  PRINTGRAPHICDESIGN     ME_PROFESSIONAL                      DESIGNER   
308945                 NaN                 NaN               EDGEN - STUDENT   
308946                 NaN                 NaN                      DESIGNER   
308947                 NaN                 NaN                      DESIGNER   

                      business_group   business_segment  \
0                          EDUCATION  EDU STUDENT STAFF   
1                          EDUCATION  EDU STUDENT STAFF   
2                           HOBBYIST              PHOTO   
3                          EDUCATION  EDU STUDENT STAFF   
4                          EDUCATION  EDU STUDENT STAFF   
...                              ...                ...   
308943  DIGITAL IMAGING PROFESSIONAL              PHOTO   
308944              DESIGN AND PRINT                SMB   
308945                     EDUCATION  EDU STUDENT STAFF   
308946              DESIGN AND PRINT         INDIVIDUAL   
308947              DESIGN AND PRINT                SMB   

                  signup_source signup_category first_cc_subscription_dts  \
0                Creative Cloud         DESKTOP          03-12-2017 11:44   
1       Renga Auto Provisioning         DESKTOP           5/29/2017 15:35   
2                    Draw (iOS)          MOBILE          06-10-2017 01:04   
3       Renga Auto Provisioning         DESKTOP           1/21/2017 18:33   
4       Renga Auto Provisioning         DESKTOP           6/23/2017 14:46   
...                         ...             ...                       ...   
308943           Creative Cloud         DESKTOP            2/14/2017 0:00   
308944  Renga Auto Provisioning         DESKTOP           2/24/2017 13:18   
308945  Renga Auto Provisioning         DESKTOP          06-11-2017 13:48   
308946               Marvel Web         SERVICE          01-06-2017 09:55   
308947           Creative Cloud         DESKTOP          03-03-2017 10:10   

       country_code                                         product_id  \
0                US                                          PHSP:APRO   
1                US                                               APRO   
2                US                                          ILST:PHSP   
3                US                                           PPRO:AME   
4                US                                               IDSN   
...             ...                                                ...   
308943           BR                                          PHSP:LTRM   
308944    

In [73]:
md.describe(include = 'all')

id extract_date     skill      job  \
count                             308948       308948    308948   144304   
unique                            308948            1         5       14   
top     ec2b63be3ca03a0f702ec1cc926ba12b   10-01-2017  BEGINNER  STUDENT   
freq                                   1       308948    131207    40501   
mean                                 NaN          NaN       NaN      NaN   
std                                  NaN          NaN       NaN      NaN   
min                                  NaN          NaN       NaN      NaN   
25%                                  NaN          NaN       NaN      NaN   
50%                                  NaN          NaN       NaN      NaN   
75%                                  NaN          NaN       NaN      NaN   
max                                  NaN          NaN       NaN      NaN   

                purpose     target_group business_group business_segment  \
count            144288           308948         308948           308923   
unique                5               38              9                6   
top     ME_PROFESSIONAL  EDGEN - STUDENT      EDUCATION       INDIVIDUAL   
freq              84504            59763          89835            94681   
mean                NaN              NaN            NaN              NaN   
std                 NaN              NaN            NaN              NaN   
min                 NaN              NaN            NaN              NaN   
25%                 NaN              NaN            NaN              NaN   
50%                 NaN              NaN            NaN              NaN   
75%                 NaN              NaN            NaN              NaN   
max                 NaN              NaN            NaN              NaN   

                  signup_source signup_category first_cc_subscription_dts  \
count                    308948          308948                    308948   
unique                      104               5                    173958   
top     Renga Auto Provisioning         DESKTOP          02-07-2017 00:00   
freq                     197649          277554                       112   
mean                        NaN             NaN                       NaN   
std                         NaN             NaN                       NaN   
min                         NaN             NaN                       NaN   
25%                         NaN             NaN                       NaN   
50%                         NaN             NaN                       NaN   
75%                         NaN             NaN                       NaN   
max                         NaN             NaN                       NaN   

       country_code product_id  download_attempts product_platforms  \
count        308948     195650      195650.000000            195650   
unique           42      32219                NaN                 3   
top              US       APRO                NaN               WIN   
freq         259525      35513                NaN            115994   
mean            NaN        NaN           4.052343               NaN   
std             NaN        NaN           9.026572               NaN   
min             NaN        NaN           1.000000               NaN   
25%             NaN        NaN           1.000000               NaN   
50%             NaN        NaN           2.000000               NaN   
75%             NaN        NaN           4.000000               NaN   
max             NaN        NaN        1933.000000               NaN   

             machines error_codes          label  
count   195650.000000       13154  308948.000000  
unique            NaN        1931            NaN  
top               NaN           6            NaN  
freq              NaN        1880            NaN  
mean         0.881119         NaN       0.053663  
std          0.884315         NaN       0.225351  
min          0.000000         NaN       0.000000  
25%          0.000000     

In [74]:
md1 = md.iloc[:, [2,3,4,5,6,7,8,9,11,12,13,14,15,17]]     
md1.head()
md1.describe(include = 'all')

skill      job          purpose     target_group business_group  \
count     308948   144304           144288           308948         308948   
unique         5       14                5               38              9   
top     BEGINNER  STUDENT  ME_PROFESSIONAL  EDGEN - STUDENT      EDUCATION   
freq      131207    40501            84504            59763          89835   
mean         NaN      NaN              NaN              NaN            NaN   
std          NaN      NaN              NaN              NaN            NaN   
min          NaN      NaN              NaN              NaN            NaN   
25%          NaN      NaN              NaN              NaN            NaN   
50%          NaN      NaN              NaN              NaN            NaN   
75%          NaN      NaN              NaN              NaN            NaN   
max          NaN      NaN              NaN              NaN            NaN   

       business_segment            signup_source signup_category country_code  \
count            308923                   308948          308948       308948   
unique                6                      104               5           42   
top          INDIVIDUAL  Renga Auto Provisioning         DESKTOP           US   
freq              94681                   197649          277554       259525   
mean                NaN                      NaN             NaN          NaN   
std                 NaN                      NaN             NaN          NaN   
min                 NaN                      NaN             NaN          NaN   
25%                 NaN                      NaN             NaN          NaN   
50%                 NaN                      NaN             NaN          NaN   
75%                 NaN                      NaN             NaN          NaN   
max                 NaN                      NaN             NaN          NaN   

       product_id  download_attempts product_platforms       machines  \
count      195650      195650.000000            195650  195650.000000   
unique      32219                NaN                 3            NaN   
top          APRO                NaN               WIN            NaN   
freq        35513                NaN            115994            NaN   
mean          NaN           4.052343               NaN       0.881119   
std           NaN           9.026572               NaN       0.884315   
min           NaN           1.000000               NaN       0.000000   
25%           NaN           1.000000               NaN       0.000000   
50%           NaN           2.000000               NaN       1.000000   
75%           NaN           4.000000               NaN       1.000000   
max           NaN        1933.000000               NaN     181.000000   

                label  
count   308948.000000  
unique            NaN  
top               NaN  
freq              NaN  
mean         0.053663  
std          0.225351  
min          0.000000  
25%          0.000000  
50%          0.000000  
75%          0.000000  
max          1.000000

# Data Cleaning

In [75]:
md1.isnull().sum()

skill                     0
job                  164644
purpose              164660
target_group              0
business_group            0
business_segment         25
signup_source             0
signup_category           0
country_code              0
product_id           113298
download_attempts    113298
product_platforms    113298
machines             113298
label                     0
dtype: int64

In [76]:
md1.purpose = md1.purpose.fillna('ME_PROFESSIONAL')
md1.job = md1.job.fillna('STUDENT')
md1.product_id = md1.product_id.fillna('APRO')
md1.download_attempts = md1.download_attempts.fillna(4)
md1.product_platforms = md1.product_platforms.fillna('WIN')
md1.business_segment = md1.business_segment.fillna('INDIVIDUAL')
md1.machines = md1.machines.fillna(1)
md1.isnull().sum()

C:\Users\Sony\Anaconda3\lib\site-packages\pandas\core\generic.py:5208: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


skill                0
job                  0
purpose              0
target_group         0
business_group       0
business_segment     0
signup_source        0
signup_category      0
country_code         0
product_id           0
download_attempts    0
product_platforms    0
machines             0
label                0
dtype: int64

In [77]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() 

In [78]:
categorical_columns = md1.select_dtypes(include = ['object']).columns
categorical_columns

Index(['skill', 'job', 'purpose', 'target_group', 'business_group',
       'business_segment', 'signup_source', 'signup_category', 'country_code',
       'product_id', 'product_platforms'],
      dtype='object')

In [79]:
md1.skill = le.fit_transform(md1.skill)                   
md1.job = le.fit_transform(md1.job)
md1.purpose = le.fit_transform(md1.purpose)
md1.target_group = le.fit_transform(md1.target_group)
md1.business_group = le.fit_transform(md1.business_group)
md1.business_segment = le.fit_transform(md1.business_segment)
md1.signup_source = le.fit_transform(md1.signup_source)
md1.country_code = le.fit_transform(md1.country_code)
md1.product_id = le.fit_transform(md1.product_id)
md1.product_platforms = le.fit_transform(md1.product_platforms)
md1.signup_category = le.fit_transform(md1.signup_category)

In [80]:
md1.head()

skill  job  purpose  target_group  business_group  business_segment  \
0      0    0        1            17               5                 1   
1      0    0        1            12               5                 1   
2      0   10        1            19               6                 4   
3      0   10        0            13               5                 1   
4      0   10        1            13               5                 1   

   signup_source  signup_category  country_code  product_id  \
0             24                1            38       24327   
1             85                1            38        7312   
2             27                3            38       17506   
3             85                1            38       28423   
4             85                1            38       12937   

   download_attempts  product_platforms  machines  label  
0                2.0                  0       1.0      0  
1                1.0                  2       0.0      0  
2                3.0                  1       1.0      0  
3                2.0                  2       1.0      0  
4                1.0                  0       0.0      0

In [81]:
#md1_x = md1.iloc[:,0:13]
#md1_y = md1.iloc[:,-1]
#md1_x.head()

# Over Sampling

In [94]:
count_0, count_1 = md1.label.value_counts()
count_0
count_1

16579

In [96]:
md1_0 = md1[md1['label'] == 0]
md1_1 = md1[md1['label'] == 1]
md1_over = md1_1.sample(count_0, replace = True)
md1_over = pd.concat([md1_over,md1_0 ], axis = 0)

In [97]:
md1_over_x = md_over.iloc[:, 0:13]     #independent variables
md1_over_y = md_over.iloc[:, -1]       #dependent varaiable
md1_over_x.head()

skill  job  purpose  target_group  business_group  business_segment  \
207073      0    6        1             7               1                 5   
65590       1   10        1            36               8                 5   
182391      0    3        1            19               6                 4   
72483       0   10        2            13               5                 0   
276551      0    7        1            31               3                 4   

        signup_source  signup_category  country_code  product_id  \
207073             91                4            38        7312   
65590              85                1            38       17931   
182391             85                1            38       20619   
72483              85                1            38       15306   
276551             46                3            38       20619   

        download_attempts  product_platforms  machines  
207073                4.0                  2       1.0  
65590                 5.0                  0       1.0  
182391                1.0                  0       1.0  
72483                 1.0                  2       0.0  
276551                1.0                  0       0.0

In [98]:
import sklearn
from sklearn.model_selection import train_test_split

In [99]:
md1_x_train,md1_x_test,md1_y_train,md1_y_test = train_test_split(md1_over_x,md1_over_y,test_size = .2, random_state = 101)

In [100]:
#md1_train = pd.concat([md1_x_train,md1_y_train],axis = 1)
#md1_test = pd.concat([md1_x_test,md1_y_test],axis = 1)

In [101]:
#count_0, count_1 = md1_train.label.value_counts()

In [102]:
#df_0 = md1_train[md1_train['label'] == 0]
#df_1 = md1_train[md1_train['label'] == 1]

In [103]:
#df_1_over = df_1.sample(count_0, replace=True)
#df_test_over = pd.concat([df_0, df_1_over],axis=0)
#df_test_over

In [104]:
#over_train,over_test,over_y_train,over_y_test = train_test_split(df_test_over,df_test_over.label,test_size = .2, random_state = 101)

# Logistic Regression

In [105]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(md1_x_train, md1_y_train)

C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [107]:
pred = logmodel.predict(md1_x_test)
pred

array([1, 0, 1, ..., 0, 1, 1], dtype=int64)

In [110]:
from sklearn.metrics import confusion_matrix
matrix1 = confusion_matrix(pred, md1_y_test)
matrix1

array([[34734, 25976],
       [23567, 32671]], dtype=int64)

In [111]:
acc1 = matrix1.diagonal().sum()/matrix1.sum()
acc1

0.5763672743441529

# Ada - Boost 

In [112]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
ada_boost  = AdaBoostClassifier(DecisionTreeClassifier(), n_estimators = 20)

In [113]:
ada_boost.fit(md1_x_train,md1_y_train)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort=False,
                                                         random_state=None,
                          

In [114]:
pred = ada_boost.predict(md1_x_test)
pred

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [115]:
from sklearn.metrics import confusion_matrix

matrix = confusion_matrix(pred, md1_y_test)
matrix

array([[49536,  9414],
       [ 8765, 49233]], dtype=int64)

In [116]:
acc = matrix.diagonal().sum()/matrix.sum()
acc

0.8445548448883264

# RandomForest

In [36]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()

In [37]:
rfc.fit(md1_x_train, md1_y_train)

C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [38]:
pred = rfc.predict(md1_x_test)
pred

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [39]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(pred, md1_y_test)
matrix

array([[50006,  9477],
       [ 8295, 49170]], dtype=int64)

In [40]:
acc = matrix.diagonal().sum()/matrix.sum()
acc

0.8480350241132811